feat: setup engine
superbet-group/trading.events.notifications pull request #18
Opened 2022-09-23 11:33 UTC by jmilic1

2022-09-23 14:11 UTC, petar-cvit requested changes

2022-09-23 14:11 UTC, petar-cvit commented on .env
> +REDIS_HOST=trading-dev.9ur0qi.0001.euc1.cache.amazonaws.com:6379
Are we reusing an existing redis? If yes should we use some other index?

2022-09-23 14:11 UTC, petar-cvit commented on internal/infrastructure/postal/postal.go
> +	return Postal{producer}
Lets make assignments of properties explicit.

2022-09-23 14:11 UTC, petar-cvit commented on internal/infrastructure/postal/postal.go
> +	"github.com/slack-go/slack"
Sort imports

2022-09-23 14:11 UTC, petar-cvit commented on internal/infrastructure/storage/reader/reader.go
> +package reader
Can we think about importing reader from trading.offer.engine in some way?

2022-09-23 14:29 UTC, jmilic1 commented on internal/infrastructure/storage/reader/reader.go
> +package reader
I'll try to remove reader and writer as components and just use go-redis directly

2022-09-26 09:45 UTC, axilis-marko commented on internal/infrastructure/storage/reader/reader.go
> +package reader
I think that the one from `trading.offer.engine` already gives us benefits such as batching. If possible, it would be good to reuse it.

2022-09-26 09:47 UTC, axilis-marko commented on .codefresh/pipelines/ci.yaml
> +  DOCKER_APP_NAME: engine
I must admit I don't know where this docker app name is used, but `engine` is to generic, better leave it as `notifications`.

2022-09-26 09:48 UTC, axilis-marko commented on internal/infrastructure/storage/reader/reader.go
> +package reader
Although we could leave it like this for setup code.

2022-12-08 08:52 UTC, jmilic1 commented
Replaced with trading.notifications.notifier

2022-12-08 08:52 UTC, closed without merging